spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wen-fei/tensquare-config.git
server:
  port: 12000
rabbitmq:
  host: 10.201.23.100
# 暴露触发消息总线的地址
management:
  endpoint:
    web:
      exposure:
        include: bus-refresh