server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.201.23.100:3306/tensquare_recruit?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true